# Generated by Django 4.0.6 on 2023-05-17 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_name', models.DateField()),
                ('private_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Private_SubModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_img', models.FileField(null=True, upload_to='Private/PrivateImage')),
                ('type', models.CharField(max_length=50)),
                ('private_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Private.privatemodel')),
            ],
        ),
    ]
